Repository LetSquad/kalita, pull requests merged in 2023-02, with the labels that each got.

#167 Добавление кнопки обновления всех портфелей
  app/main.ts
  build/icon.png
  package-lock.json
  package.json
  src/apis/moexApi.ts
  src/components/BrokeragePortfolioTable/AdditionalHeader/AdditionalHeader.tsx
  src/components/BrokeragePortfolioTable/AdditionalHeader/AdditionalHeaderMenu.tsx
  src/components/BrokeragePortfolioTable/AdditionalHeader/SettingsModal/ModelPortfolioTabs/ModelPortfolioDataSourcesSelector.tsx
  src/components/BrokeragePortfolioTable/Table.tsx
  src/components/Dashboard/SidebarMenu/SidebarMenu.tsx
  src/components/Dashboard/SidebarMenu/SidebarMenuElement.tsx
  src/components/Dashboard/SidebarMenu/styles/SidebarMenu.scss
  src/components/DataTable/Cell/FormatterCell/DataTableFormatterCell.tsx
  src/components/DataTable/Cell/utils/formatterUtils.ts
  src/components/DataTable/types/formatter.ts
  src/components/DataTable/utils/utils.ts
  src/store/electronCache/electronCacheReducer.ts
  src/store/portfolios/portfoliosReducer.ts
  src/store/portfolios/portfoliosReducerHelper.ts
  src/store/portfolios/selectors.ts
  src/utils/currencyUtils.ts
  src/workers/BrokerReportLoader.worker.ts
Labels: enhancement

#166 add AnalyticsTable
  src/components/Analytics/AdditionalHeader/AdditionalHeader.tsx
  src/components/Analytics/AdditionalHeader/styles/AdditionalHeader.scss
  src/components/Analytics/Analytics.tsx
  src/components/Analytics/AnalyticsChart/AnalyticsChart.tsx
  src/components/Analytics/AnalyticsChart/styles/AnalyticsChart.scss
  src/components/Analytics/AnalyticsTable/AnalyticsTable.tsx
  src/components/Analytics/AnalyticsTable/columns.tsx
  src/components/Analytics/AnalyticsTable/styles/AnalyticsTable.scss
  src/components/Analytics/styles/Analytics.scss
  src/components/Analytics/utils/getPortfoliosChartData.ts
  src/components/BrokeragePortfolioTable/DividendsModal.tsx
  src/components/BrokeragePortfolioTable/Table.tsx
  src/models/analytics/types.ts
  src/models/constants.ts
  src/models/table/enums.ts
  src/store/sidebarMenu/sidebarMenuReducerHelper.ts
Labels: enhancement

#177 Обновление значения инпута в ячейки при обновлении данных
  src/components/DataTable/Edit/DataTableInput.tsx
  src/index.tsx
Labels: bug, enhancement

#175 fix broker reports parsing
  src/utils/report/openBrokerReoprtUtils.ts
  src/utils/report/vtbBrokerReportUtils.ts
Labels: bug

#173 add analytics foreign currencies support (#169)
  src/apis/moexApi.ts
  src/components/Analytics/AdditionalHeader/AdditionalHeader.tsx
  src/components/Analytics/AdditionalHeader/styles/AdditionalHeader.scss
  src/components/Analytics/Analytics.tsx
  src/components/Analytics/AnalyticsChart/AnalyticsChart.tsx
  src/components/Analytics/AnalyticsTable/AnalyticsTable.tsx
  src/components/Analytics/AnalyticsTable/columns.tsx
  src/components/Analytics/utils/getPortfoliosChartData.ts
  src/store/portfolios/portfoliosReducerHelper.ts
  src/utils/currencyUtils.ts
Labels: enhancement

#180 Добавлено форматирование значений в инпутах с форматированием
  src/components/DataTable/Cell/FormatterCell/DataTableMoneyFormatterCell.tsx
  src/components/DataTable/Cell/FormatterCell/DataTablePercentageFormatterCell.tsx
  src/components/DataTable/Edit/DataTableInput.tsx
  src/components/DataTable/types/edit.ts
Labels: bug

#181 Revert "Добавлено форматирование значений в инпутах с форматированием"
  src/components/DataTable/Cell/FormatterCell/DataTableMoneyFormatterCell.tsx
  src/components/DataTable/Cell/FormatterCell/DataTablePercentageFormatterCell.tsx
  src/components/DataTable/Edit/DataTableInput.tsx
  src/components/DataTable/types/edit.ts
Labels: bug

#182 Добавлено форматирование значений в инпутах при просмотре
  src/components/Analytics/AdditionalHeader/AdditionalHeader.tsx
  src/components/Analytics/AnalyticsChart/AnalyticsChart.tsx
  src/components/Analytics/AnalyticsTable/AnalyticsTable.tsx
  src/components/Analytics/utils/getPortfoliosChartData.ts
  src/components/BrokeragePortfolioTable/AdditionalHeader/AdditionalHeader.tsx
  src/components/BrokeragePortfolioTable/AdditionalHeader/AdditionalHeaderMenu.tsx
  src/components/BrokeragePortfolioTable/BrokerTable/BrokerTable.tsx
  src/components/BrokeragePortfolioTable/ModelTable/ModelTable.tsx
  src/components/BrokeragePortfolioTable/ModelTable/styles/TargetAmountInput.scss
  src/components/BrokeragePortfolioTable/Table.tsx
  src/components/BrokeragePortfolioTable/columns.tsx
  src/components/Dashboard/DashboardContent.tsx
  src/components/DataTable/Cell/FormatterCell/DataTableMoneyFormatterCell.tsx
  src/components/DataTable/Cell/FormatterCell/DataTablePercentageFormatterCell.tsx
  src/components/DataTable/Cell/utils/formatterUtils.ts
  src/components/DataTable/Edit/DataTableInput.tsx
  src/components/DataTable/types/edit.ts
  src/components/DataTable/types/formatter.ts
  src/components/Settings/SettingsMenu.tsx
  src/components/Settings/SettingsModal/BrokerAccountTabs/BrokerAccountReportParser.tsx
  src/components/Settings/SettingsModal/BrokerAccountTabs/styles/BrokerAccountReportParser.scss
  src/components/Settings/SettingsModal/CommonTabs/CommonSettings.tsx
  src/components/Settings/SettingsModal/ModelPortfolioTabs/ModelPortfolioDataSourcesSelector.tsx
  src/components/Settings/SettingsModal/SettingsModal.tsx
  src/components/Settings/SettingsModal/styles/SettingsModal.scss
  src/components/Settings/styles/AdditionalHeaderMenu.scss
  src/components/utils/WithSaving.tsx
  src/models/portfolios/types.ts
  src/models/settings/enums.ts
  src/store/index.ts
  src/store/portfolios/portfoliosReducer.ts
  src/store/settings/settingsReducer.ts
Labels: bug

#183 fix portfolios position quantity update (#174)
  src/store/portfolios/portfoliosReducer.ts
Labels: bug
